//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CMS.WSCMS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSCMSSoap", Namespace="http://tempuri.org/")]
    public partial class WSCMS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetNovedadesAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadArchivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConvertBlobToByteOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback NovedadLoadAllByDescripcionOperationCompleted;
        
        private System.Threading.SendOrPostCallback NovedadDeleteLogicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSCMS() {
            this.Url = global::CMS.Properties.Settings.Default.CMS_WSCMS_WSCMS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetNovedadesAllCompletedEventHandler GetNovedadesAllCompleted;
        
        /// <remarks/>
        public event LoadCompletedEventHandler LoadCompleted;
        
        /// <remarks/>
        public event LoadArchivoCompletedEventHandler LoadArchivoCompleted;
        
        /// <remarks/>
        public event ConvertBlobToByteCompletedEventHandler ConvertBlobToByteCompleted;
        
        /// <remarks/>
        public event SaveCompletedEventHandler SaveCompleted;
        
        /// <remarks/>
        public event NovedadLoadAllByDescripcionCompletedEventHandler NovedadLoadAllByDescripcionCompleted;
        
        /// <remarks/>
        public event NovedadDeleteLogicoCompletedEventHandler NovedadDeleteLogicoCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNovedadesAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Novedad[] GetNovedadesAll() {
            object[] results = this.Invoke("GetNovedadesAll", new object[0]);
            return ((Novedad[])(results[0]));
        }
        
        /// <remarks/>
        public void GetNovedadesAllAsync() {
            this.GetNovedadesAllAsync(null);
        }
        
        /// <remarks/>
        public void GetNovedadesAllAsync(object userState) {
            if ((this.GetNovedadesAllOperationCompleted == null)) {
                this.GetNovedadesAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNovedadesAllOperationCompleted);
            }
            this.InvokeAsync("GetNovedadesAll", new object[0], this.GetNovedadesAllOperationCompleted, userState);
        }
        
        private void OnGetNovedadesAllOperationCompleted(object arg) {
            if ((this.GetNovedadesAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNovedadesAllCompleted(this, new GetNovedadesAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Load", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Novedad Load(int id) {
            object[] results = this.Invoke("Load", new object[] {
                        id});
            return ((Novedad)(results[0]));
        }
        
        /// <remarks/>
        public void LoadAsync(int id) {
            this.LoadAsync(id, null);
        }
        
        /// <remarks/>
        public void LoadAsync(int id, object userState) {
            if ((this.LoadOperationCompleted == null)) {
                this.LoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadOperationCompleted);
            }
            this.InvokeAsync("Load", new object[] {
                        id}, this.LoadOperationCompleted, userState);
        }
        
        private void OnLoadOperationCompleted(object arg) {
            if ((this.LoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadCompleted(this, new LoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadArchivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] LoadArchivo(int id) {
            object[] results = this.Invoke("LoadArchivo", new object[] {
                        id});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void LoadArchivoAsync(int id) {
            this.LoadArchivoAsync(id, null);
        }
        
        /// <remarks/>
        public void LoadArchivoAsync(int id, object userState) {
            if ((this.LoadArchivoOperationCompleted == null)) {
                this.LoadArchivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadArchivoOperationCompleted);
            }
            this.InvokeAsync("LoadArchivo", new object[] {
                        id}, this.LoadArchivoOperationCompleted, userState);
        }
        
        private void OnLoadArchivoOperationCompleted(object arg) {
            if ((this.LoadArchivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadArchivoCompleted(this, new LoadArchivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConvertBlobToByte", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ConvertBlobToByte(string sql) {
            object[] results = this.Invoke("ConvertBlobToByte", new object[] {
                        sql});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void ConvertBlobToByteAsync(string sql) {
            this.ConvertBlobToByteAsync(sql, null);
        }
        
        /// <remarks/>
        public void ConvertBlobToByteAsync(string sql, object userState) {
            if ((this.ConvertBlobToByteOperationCompleted == null)) {
                this.ConvertBlobToByteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConvertBlobToByteOperationCompleted);
            }
            this.InvokeAsync("ConvertBlobToByte", new object[] {
                        sql}, this.ConvertBlobToByteOperationCompleted, userState);
        }
        
        private void OnConvertBlobToByteOperationCompleted(object arg) {
            if ((this.ConvertBlobToByteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConvertBlobToByteCompleted(this, new ConvertBlobToByteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Save", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Novedad Save(Novedad nov) {
            object[] results = this.Invoke("Save", new object[] {
                        nov});
            return ((Novedad)(results[0]));
        }
        
        /// <remarks/>
        public void SaveAsync(Novedad nov) {
            this.SaveAsync(nov, null);
        }
        
        /// <remarks/>
        public void SaveAsync(Novedad nov, object userState) {
            if ((this.SaveOperationCompleted == null)) {
                this.SaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveOperationCompleted);
            }
            this.InvokeAsync("Save", new object[] {
                        nov}, this.SaveOperationCompleted, userState);
        }
        
        private void OnSaveOperationCompleted(object arg) {
            if ((this.SaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCompleted(this, new SaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NovedadLoadAllByDescripcion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Novedad[] NovedadLoadAllByDescripcion(string descripcion) {
            object[] results = this.Invoke("NovedadLoadAllByDescripcion", new object[] {
                        descripcion});
            return ((Novedad[])(results[0]));
        }
        
        /// <remarks/>
        public void NovedadLoadAllByDescripcionAsync(string descripcion) {
            this.NovedadLoadAllByDescripcionAsync(descripcion, null);
        }
        
        /// <remarks/>
        public void NovedadLoadAllByDescripcionAsync(string descripcion, object userState) {
            if ((this.NovedadLoadAllByDescripcionOperationCompleted == null)) {
                this.NovedadLoadAllByDescripcionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNovedadLoadAllByDescripcionOperationCompleted);
            }
            this.InvokeAsync("NovedadLoadAllByDescripcion", new object[] {
                        descripcion}, this.NovedadLoadAllByDescripcionOperationCompleted, userState);
        }
        
        private void OnNovedadLoadAllByDescripcionOperationCompleted(object arg) {
            if ((this.NovedadLoadAllByDescripcionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NovedadLoadAllByDescripcionCompleted(this, new NovedadLoadAllByDescripcionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NovedadDeleteLogico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int NovedadDeleteLogico(Novedad nov) {
            object[] results = this.Invoke("NovedadDeleteLogico", new object[] {
                        nov});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void NovedadDeleteLogicoAsync(Novedad nov) {
            this.NovedadDeleteLogicoAsync(nov, null);
        }
        
        /// <remarks/>
        public void NovedadDeleteLogicoAsync(Novedad nov, object userState) {
            if ((this.NovedadDeleteLogicoOperationCompleted == null)) {
                this.NovedadDeleteLogicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNovedadDeleteLogicoOperationCompleted);
            }
            this.InvokeAsync("NovedadDeleteLogico", new object[] {
                        nov}, this.NovedadDeleteLogicoOperationCompleted, userState);
        }
        
        private void OnNovedadDeleteLogicoOperationCompleted(object arg) {
            if ((this.NovedadDeleteLogicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NovedadDeleteLogicoCompleted(this, new NovedadDeleteLogicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Update(Novedad nov) {
            object[] results = this.Invoke("Update", new object[] {
                        nov});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(Novedad nov) {
            this.UpdateAsync(nov, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(Novedad nov, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        nov}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Novedad {
        
        private int nov_identificadorField;
        
        private string mensajeField;
        
        private System.DateTime fechaAltaField;
        
        private System.DateTime fechaBajaField;
        
        private System.DateTime fechaModificacionField;
        
        private byte[] archivoField;
        
        private string mensaje_webField;
        
        private string tituloField;
        
        private int idUsuAltaField;
        
        private int idUsuBajaField;
        
        private int idUsuModField;
        
        private int tipoField;
        
        private string archivo_extField;
        
        private string archivo_nombreField;
        
        private int archivo_tam_kbField;
        
        private string descripcion_breveField;
        
        private bool es_imagenField;
        
        private bool es_historicaField;
        
        /// <comentarios/>
        public int nov_identificador {
            get {
                return this.nov_identificadorField;
            }
            set {
                this.nov_identificadorField = value;
            }
        }
        
        /// <comentarios/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime fechaAlta {
            get {
                return this.fechaAltaField;
            }
            set {
                this.fechaAltaField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime fechaBaja {
            get {
                return this.fechaBajaField;
            }
            set {
                this.fechaBajaField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime fechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
            }
        }
        
        /// <comentarios/>
        public string mensaje_web {
            get {
                return this.mensaje_webField;
            }
            set {
                this.mensaje_webField = value;
            }
        }
        
        /// <comentarios/>
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <comentarios/>
        public int idUsuAlta {
            get {
                return this.idUsuAltaField;
            }
            set {
                this.idUsuAltaField = value;
            }
        }
        
        /// <comentarios/>
        public int idUsuBaja {
            get {
                return this.idUsuBajaField;
            }
            set {
                this.idUsuBajaField = value;
            }
        }
        
        /// <comentarios/>
        public int idUsuMod {
            get {
                return this.idUsuModField;
            }
            set {
                this.idUsuModField = value;
            }
        }
        
        /// <comentarios/>
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <comentarios/>
        public string archivo_ext {
            get {
                return this.archivo_extField;
            }
            set {
                this.archivo_extField = value;
            }
        }
        
        /// <comentarios/>
        public string archivo_nombre {
            get {
                return this.archivo_nombreField;
            }
            set {
                this.archivo_nombreField = value;
            }
        }
        
        /// <comentarios/>
        public int archivo_tam_kb {
            get {
                return this.archivo_tam_kbField;
            }
            set {
                this.archivo_tam_kbField = value;
            }
        }
        
        /// <comentarios/>
        public string descripcion_breve {
            get {
                return this.descripcion_breveField;
            }
            set {
                this.descripcion_breveField = value;
            }
        }
        
        /// <comentarios/>
        public bool es_imagen {
            get {
                return this.es_imagenField;
            }
            set {
                this.es_imagenField = value;
            }
        }
        
        /// <comentarios/>
        public bool es_historica {
            get {
                return this.es_historicaField;
            }
            set {
                this.es_historicaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetNovedadesAllCompletedEventHandler(object sender, GetNovedadesAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNovedadesAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNovedadesAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Novedad[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Novedad[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void LoadCompletedEventHandler(object sender, LoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Novedad Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Novedad)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void LoadArchivoCompletedEventHandler(object sender, LoadArchivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadArchivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadArchivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ConvertBlobToByteCompletedEventHandler(object sender, ConvertBlobToByteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConvertBlobToByteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConvertBlobToByteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void SaveCompletedEventHandler(object sender, SaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Novedad Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Novedad)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void NovedadLoadAllByDescripcionCompletedEventHandler(object sender, NovedadLoadAllByDescripcionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NovedadLoadAllByDescripcionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NovedadLoadAllByDescripcionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Novedad[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Novedad[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void NovedadDeleteLogicoCompletedEventHandler(object sender, NovedadDeleteLogicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NovedadDeleteLogicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NovedadDeleteLogicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591